version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: >
      bash -c "
      python manage.py migrate
      && python manage.py test
      && python manage.py import_dummy
      && python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    volumes:
      - .data/db:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

